### ISSUE TITLE
V2.0.0 todo items

### ISSUE THREAD

**Issue by cnizzardini** [mixerapi/mixerapi-dev#148]
- [ ] Update skeleton: https://github.com/mixerapi/app
- [ ] Update documentation
- [ ] Need figure out how to display v1 and v2 docs at same time
- [ ] Get automated documentation deployment working again
